/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pw.sap.pojo.Contabilidad;
import pw.sap.pojo.Contabilidad.*;
import com.itextpdf.text.Anchor;
import com.itextpdf.text.BadElementException;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chapter;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.List;
import com.itextpdf.text.ListItem;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Section;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.Properties;

/**
 *
 * @author montse
 */
public class Reporte_ER {
    Connection conn;

    private static String FILE = "/home/montse/reporte/reporte-EstadoResult.pdf";

    private static Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 18,
            Font.BOLD);
    private static Font redFont = new Font(Font.FontFamily.TIMES_ROMAN, 12,
            Font.NORMAL, BaseColor.RED);
    private static Font subFont = new Font(Font.FontFamily.TIMES_ROMAN, 16,
            Font.BOLD);
    private static Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12,
            Font.BOLD);

    public Reporte_ER() throws ClassNotFoundException, SQLException {
        Class.forName("org.postgresql.Driver");
    }

    /**
     * inicio de conexion de la base de datos con postgres
     *
     * @throws SQLException
     */
    public void openDB() throws SQLException {
        Properties connProp = new Properties();
        connProp.put("user", "postgres");
        connProp.put("password", "root");
        conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/sap", connProp);
    }

    /**
     * Cierra la conexión con la base de datos
     *
     * @throws SQLException
     */
    public void closeDB() throws SQLException {
        conn.close();
    }

    public void generarReporte() {

        try {
            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream(FILE));
            document.open();
            addMetaData(document);
            addTitlePage(document);
            addContent(document);
            document.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private static void addMetaData(Document document) {
        document.addTitle("Reporte Gerencial");
        document.addSubject("Using iText");
        document.addKeywords("Java, PDF, iText");
        document.addAuthor("Lars Vogel");
        document.addCreator("Lars Vogel");
    }

    private static void addTitlePage(Document document)
            throws DocumentException {
        Paragraph preface = new Paragraph();
        // We add one empty line
        addEmptyLine(preface, 1);
        // Lets write a big header
        preface.add(new Paragraph("Reporte Contabilidad-Estado de Resultados", catFont));

        addEmptyLine(preface, 1);
        // Will create: Report generated by: _name, _date
        preface.add(new Paragraph(
                "Report generated by: " + System.getProperty("user.name") + ", " + new Date(), //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
                smallBold));
        addEmptyLine(preface, 3);
        preface.add(new Paragraph(
                "El siguiente reporte mostrara el Estado de Resultados de la empresa, así como una tabla especifíca ",
                smallBold));

        addEmptyLine(preface, 8);

        preface.add(new Paragraph(
                "This document is a preliminary version and not subject to your license agreement or any other agreement with SAPito.com",
                redFont));

        document.add(preface);
        // Start a new page
        document.newPage();
    }

    private static void addContent(Document document) throws DocumentException, SQLException {
        Anchor anchor = new Anchor("Contabilidad", catFont);
        anchor.setName("primer parte");

        // Second parameter is the number of the chapter
        Chapter catPart = new Chapter(new Paragraph(anchor), 1);

        Paragraph subPara = new Paragraph("Plan de cuentas", subFont);
        Section subCatPart = catPart.addSection(subPara);
//        subCatPart.add(new Paragraph("Hello"));

//        subPara = new Paragraph("Subcategory 2", subFont);
//        subCatPart = catPart.addSection(subPara);
//        subCatPart.add(new Paragraph("Paragraph 1"));
//        subCatPart.add(new Paragraph("Paragraph 2"));
//        subCatPart.add(new Paragraph("Paragraph 3"));

        // add a list
        createList(subCatPart);
        Paragraph paragraph = new Paragraph();
        addEmptyLine(paragraph, 5);
        subCatPart.add(paragraph);

        // add a table
        createTabla(subCatPart);

        // now add all this to the document
        document.add(catPart);

        // Next section
        anchor = new Anchor("Segunda parte", catFont);
        anchor.setName("Asientos Generales");
        createList(subCatPart);
        addEmptyLine(paragraph, 5);
        subCatPart.add(paragraph);

        // Second parameter is the number of the chapter
        
        
        createTables(subCatPart);
        createTablas(subCatPart);
//        subPara = new Paragraph("Subcategory", subFont);
//        subCatPart = catPart.addSection(subPara);
//        subCatPart.add(new Paragraph("This is a very important message"));

        // now add all this to the document
        document.add(catPart);
        
        anchor = new Anchor("Tercera parte", catFont);
        anchor.setName("Asientos detalles");
         catPart = new Chapter(new Paragraph(anchor), 1);
         createList(subCatPart);
        addEmptyLine(paragraph, 5);
        subCatPart.add(paragraph);
        
        createTable(subCatPart);
        createTabl(subCatPart);
         document.add(catPart);
        

    }

    private static void createTable(Section subCatPart)
            throws BadElementException, SQLException {
        PdfPTable table = new PdfPTable(4);

        // t.setBorderColor(BaseColor.GRAY);
        // t.setPadding(4);
        // t.setSpacing(4);
        // t.setBorderWidth(1);

        PdfPCell c1 = new PdfPCell(new Phrase("ID GENERAL",redFont));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("FECHA DE FACTURA ",redFont));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("CUENTA CARGO",redFont));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("CUENTA ABONO",redFont));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

    ResultSet rsTabla = consultaGreporte();
        while (rsTabla.next())
        {
            table.setHeaderRows(1);

            table.addCell(rsTabla.getString(1));
            table.addCell(rsTabla.getString(2));
            table.addCell(rsTabla.getString(3));
            table.addCell(rsTabla.getString(4));
        }

        subCatPart.add(table);
    }

    public static ResultSet consultaGreporte() throws SQLException
    {
        Connection conn;
        Properties connProp = new Properties();
        connProp.put("user", "postgres");
        connProp.put("password", "root");
        conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/BDSAPPW", connProp);

        PreparedStatement ps;

        ps = conn.prepareStatement("select id_general,fecha_fac,cuenta_cargo,cuenta_abono\n"
                + "                                                    from asientodetalle ");
        ResultSet rs = ps.executeQuery();

        System.out.println(ps);

        conn.close();
        return rs;
    }    
private static void createTabl(Section subCatPart)
            throws BadElementException, SQLException
    {
        PdfPTable table = new PdfPTable(4);

        // t.setBorderColor(BaseColor.GRAY);
        // t.setPadding(4);
        // t.setSpacing(4);
        // t.setBorderWidth(1);
        PdfPCell c1 = new PdfPCell(new Phrase("MONTO",redFont));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);
        
        c1 = new PdfPCell(new Phrase("DESCRIPCIÓN",redFont));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);
        
        c1 = new PdfPCell(new Phrase("DEDUCIBLE",redFont));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);
        
        c1 = new PdfPCell(new Phrase("FOLIO FISCAL",redFont));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);
        ResultSet rsTabla = consultaGreporte2();
        while (rsTabla.next())
        {
            table.setHeaderRows(1);

            table.addCell(rsTabla.getString(1));
            table.addCell(rsTabla.getString(2));
            table.addCell(rsTabla.getString(3));
            table.addCell(rsTabla.getString(4));
        }

        subCatPart.add(table);
    }

    public static ResultSet consultaGreporte2() throws SQLException
    {
        Connection conn;
        Properties connProp = new Properties();
        connProp.put("user", "postgres");
        connProp.put("password", "root");
        conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/BDSAPPW", connProp);

        PreparedStatement ps;

        ps = conn.prepareStatement("select monto,descripcion,deducible, folio_fiscal\n"
                + "                                                    from asientodetalle ");
        ResultSet rs = ps.executeQuery();

        System.out.println(ps);

        conn.close();
        return rs;
    }

    private static void createTables(Section subCatPart)
            throws BadElementException, SQLException
    {
        PdfPTable table = new PdfPTable(4);

        // t.setBorderColor(BaseColor.GRAY);
        // t.setPadding(4);
        // t.setSpacing(4);
        // t.setBorderWidth(1);
        PdfPCell c1 = new PdfPCell(new Phrase("ID",redFont));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);
        
        c1 = new PdfPCell(new Phrase("MODULO",redFont));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);
        
        c1 = new PdfPCell(new Phrase("TIPO DE COMPROBANTE",redFont));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);
        
        c1 = new PdfPCell(new Phrase("FECHA DE APLICACIÓN",redFont));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);
        ResultSet rsTabla = consultaGreporte3();
        while (rsTabla.next())
        {
            table.setHeaderRows(1);

            table.addCell(rsTabla.getString(1));
            table.addCell(rsTabla.getString(2));
            table.addCell(rsTabla.getString(3));
            table.addCell(rsTabla.getString(4));
        }

        subCatPart.add(table);
    }

    public static ResultSet consultaGreporte3() throws SQLException
    {
        Connection conn;
        Properties connProp = new Properties();
        connProp.put("user", "postgres");
        connProp.put("password", "root");
        conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/BDSAPPW", connProp);

        PreparedStatement ps;

        ps = conn.prepareStatement("select id,modulo,tipo_comprobante, fecha_apli\n"
                + "                                                    from asientogeneral ");
        ResultSet rs = ps.executeQuery();

        System.out.println(ps);

        conn.close();
        return rs;
    }

private static void createTablas(Section subCatPart)
            throws BadElementException, SQLException
    {
        PdfPTable table = new PdfPTable(2);

        // t.setBorderColor(BaseColor.GRAY);
        // t.setPadding(4);
        // t.setSpacing(4);
        // t.setBorderWidth(1);
        PdfPCell c1 = new PdfPCell(new Phrase("CONCEPTO",redFont));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);
        
        c1 = new PdfPCell(new Phrase("PERIODO CONTABLE",redFont));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);
        
        
        ResultSet rsTabla = consultaGreporte4();
        while (rsTabla.next())
        {
            table.setHeaderRows(1);

            table.addCell(rsTabla.getString(1));
            table.addCell(rsTabla.getString(2));
            
        }

        subCatPart.add(table);
    }

    public static ResultSet consultaGreporte4() throws SQLException
    {
        Connection conn;
        Properties connProp = new Properties();
        connProp.put("user", "postgres");
        connProp.put("password", "root");
        conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/BDSAPPW", connProp);

        PreparedStatement ps;

        ps = conn.prepareStatement("select concepto,periodo_conta\n"
                + "                                                    from asientogeneral ");
        ResultSet rs = ps.executeQuery();

        System.out.println(ps);

        conn.close();
        return rs;
    }  
    private static void createTabla(Section subCatPart)
            throws BadElementException, SQLException
    {
        PdfPTable table = new PdfPTable(3);

        // t.setBorderColor(BaseColor.GRAY);
        // t.setPadding(4);
        // t.setSpacing(4);
        // t.setBorderWidth(1);
        PdfPCell c1 = new PdfPCell(new Phrase("ID",redFont));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);
        
        c1 = new PdfPCell(new Phrase("CUENTA",redFont));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);
        c1 = new PdfPCell(new Phrase("DESCRIPCIÓN",redFont));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);
        
        ResultSet rsTabla = consultaGreporte5();
        while (rsTabla.next())
        {
            table.setHeaderRows(1);

            table.addCell(rsTabla.getString(1));
            table.addCell(rsTabla.getString(2));
            table.addCell(rsTabla.getString(3));
            
        }

        subCatPart.add(table);
    }

    public static ResultSet consultaGreporte5() throws SQLException
    {
        Connection conn;
        Properties connProp = new Properties();
        connProp.put("user", "postgres");
        connProp.put("password", "root");
        conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/BDSAPPW", connProp);

        PreparedStatement ps;

        ps = conn.prepareStatement("select id,cuenta,descripcion\n"
                + "                                                    from cuenta_sat ");
        ResultSet rs = ps.executeQuery();

        System.out.println(ps);

        conn.close();
        return rs;
    } 

    private static void createList(Section subCatPart) {
        List list = new List(true, false, 10);
        list.add(new ListItem("First point"));
        list.add(new ListItem("Second point"));
        list.add(new ListItem("Third point"));
        subCatPart.add(list);
    }

    private static void addEmptyLine(Paragraph paragraph, int number) {
        for (int i = 0; i < number; i++) {
            paragraph.add(new Paragraph(" "));
        }
    }

}

